# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-10-22 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20181022_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='create_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='modified_time',
            field=models.DateField(),
        ),
    ]
